apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: redis-cluster
  ports:
    - name: redis
      port: 6379           # Service port inside the cluster
      targetPort: 6379     # Container port
      nodePort: 32005      # NodePort (must be 30000â€“32767)
      protocol: TCP